name: CI

on:
  push:
    branches:
      - master
jobs:
  first_job_id:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: first step on first job
        run: echo "first step"
        shell: bash
      - name: build docker image
        run: docker build -t tsaeki/test_github_actions .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: push docker image
        uses: actions/docker/cli@master
        with:
          args: "push tsaeki/test_github_actions"
