name: CI

on:
  push:
    branches:
      - master
jobs:
  test_docker_push:
    name: test docker push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t tsaeki/test_github_actions .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: push docker image
        uses: actions/docker/cli@master
        with:
          args: "push tsaeki/test_github_actions"
