name: CI

on:
  push:
    branches:
      - master
jobs:
  first_job_id:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: first step on first job
        run: echo "first step"
        shell: bash
      - name: build docker image
        run: docker build -t tsaeki/test_github_actions .
      - name: push docker image
        # run: docker login && docker push tsaeki/test_github_actions
        run: echo ${dockerhub_username}
        env:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
